package org.drunkuncle.discify.model

data class Label(val label: String,
                 val series: String,
                 val catalogNumber: String,
                 val recordCompany: String,
                 val licensedTo: String,
                 val licensedFrom: String,
                 val licensedThrough: String,
                 val marketedBy: String,
                 val distributedBy: String,
                 val manufacturedBy: String,
                 val exportedBy: String,
                 val producedFor: String,
                 val manufacturedFor: String,
                 val recordedBy: String,
                 val phonographicCopyright: String,
                 val copyright: String,
                 val madeBy: String,
                 val pressedBy: String,
                 val duplicatedBy: String,
                 val printedBy: String,
                 val publishedBy: String,
                 val recordedAt: String,
                 val engineeredAt: String,
                 val overdubbedAt: String,
                 val producedAt: String,
                 val mixedAt: String,
                 val remixedAt: String,
                 val editedAt: String,
                 val masteredAt: String,
                 val remasteredAt: String,
                 val lacquerCutAt: String,
                 val glassMasteredAt: String,
                 val designedAt: String,
                 val filmedAt: String,
                 val exclusiveRetailer: String)